
[2017-12-08 16:39:53] Traceback (most recent call last):

  File "javascript_dialog_handler.pyx", line 109, in cefpython_py27.JavascriptDialogHandler_OnResetJavascriptDialogState (cefpython.cpp:75136)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 1075, in OnResetJavascriptDialogState
    print("[wxpython_viewer.py] OnResetDialogState()")

IOError: [Errno 9] Bad file descriptor


[2017-12-08 17:05:05] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

TypeError: send_error_reports() takes no arguments (1 given)


[2017-12-08 17:05:22] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

TypeError: get_updates() takes no arguments (1 given)


[2017-12-08 17:17:33] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

TypeError: send_error_reports() takes no arguments (1 given)


[2017-12-08 17:21:52] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

TypeError: send_error_reports() takes no arguments (1 given)


[2017-12-08 17:26:40] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

TypeError: send_error_reports() takes no arguments (1 given)


[2017-12-08 17:44:56] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

TypeError: send_error_reports() takes exactly 1 argument (2 given)


[2017-12-08 18:28:57] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 594, in send_error_reports
    loc = dirname(__file__)

NameError: global name 'dirname' is not defined


[2017-12-08 18:34:46] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 594, in send_error_reports
    loc = dirname(__file__)

NameError: global name 'dirname' is not defined


[2017-12-08 18:37:25] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 594, in send_error_reports
    loc = dirname(__file__)

NameError: global name 'dirname' is not defined


[2017-12-08 18:38:06] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 594, in send_error_reports
    loc = dirname(__file__)

NameError: global name 'dirname' is not defined


[2017-12-08 19:00:03] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 594, in send_error_reports
    loc = dirname(__file__)

NameError: global name 'dirname' is not defined


[2017-12-08 19:03:51] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 594, in send_error_reports
    loc = dirname(__file__)

NameError: global name 'dirname' is not defined


[2017-12-08 19:08:02] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 594, in send_error_reports
    loc = dirname(__file__)

NameError: global name 'dirname' is not defined


[2017-12-08 19:08:25] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 594, in send_error_reports
    loc = dirname(__file__)

NameError: global name 'dirname' is not defined


[2017-12-08 19:09:53] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 606, in send_error_reports
    files = {'zipFile' : open(file_name) }

IOError: [Errno 2] No such file or directory: 'C:\\MMELC_pilot\\python\\error_reports.zip'


[2017-12-08 19:15:45] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 606, in send_error_reports
    files = {'zipFile' : open(file_name) }

IOError: [Errno 2] No such file or directory: 'C:\\MMELC_pilot\\python\\error_reports.zip'


[2017-12-08 19:16:15] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 606, in send_error_reports
    files = {'zipFile' : open(file_name) }

IOError: [Errno 2] No such file or directory: 'C:\\MMELC_pilot\\python\\error_reports.zip'


[2017-12-08 19:18:06] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 618, in send_error_reports
    except Exception(e):

NameError: global name 'e' is not defined


[2017-12-08 19:18:25] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 606, in send_error_reports
    files = {'zipFile' : open(file_name) }

IOError: [Errno 2] No such file or directory: 'C:\\MMELC_pilot\\python\\error_reports.zip'


[2017-12-08 19:19:28] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 606, in send_error_reports
    files = {'zipFile' : open(file_name) }

IOError: [Errno 2] No such file or directory: 'C:\\MMELC_pilot\\python\\error_reports.zip'


[2017-12-08 19:20:09] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 606, in send_error_reports
    files = {'zipFile' : open(file_name) }

IOError: [Errno 2] No such file or directory: 'C:\\MMELC_pilot\\python\\error_reports.zip'


[2017-12-08 19:22:25] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 607, in send_error_reports
    except Exception(e):

NameError: global name 'e' is not defined


[2017-12-08 19:22:58] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 620, in send_error_reports
    except Exception(e):

NameError: global name 'e' is not defined


[2017-12-08 19:23:40] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 620, in send_error_reports
    except Exception(e):

NameError: global name 'e' is not defined


[2017-12-08 19:24:03] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 620, in send_error_reports
    except Exception(e):

NameError: global name 'e' is not defined


[2017-12-08 19:25:29] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 607, in send_error_reports
    except Exception(e):

NameError: global name 'e' is not defined


[2017-12-08 19:26:19] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "C:\MMELC_pilot\python\wxpython_viewer.py", line 607, in send_error_reports
    except Exception(e):

NameError: global name 'e' is not defined

